package tests.notlar;

public class Notlar {

    /*
    1- PRIORITY YAZILMAYAN METHODLAR EN BASTA CALISIR
    2- PRIORITY YAZILAN METHODLAR ISE ; VERILEN ONCELIK SIRASINA GORE CALISIR
    3- EGER HERHANGI BIR PRIORITY VERILMEDIYSE ALFABETIK SIRAYA GORE CALISIR.
 */

}
